<a href="https://colab.research.google.com/github/MhdsHosseini/Deep_Learning_F20_Assignments/blob/master/Ass03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment 03**

Mahdis Hosseini

In [2]:
import numpy as np
import torch
import h5py

Creat Tensors

In [13]:
T33=torch.rand(3,3, dtype=torch.float)
T44=torch.rand(4,4, dtype=torch.double)
T534=torch.randint(0, 200, (5, 3, 4), dtype=torch.short)

Change Elements

In [14]:
T33=T33.cuda()
T33=T33*0.1
T33

tensor([[0.0286, 0.0207, 0.0570],
        [0.0612, 0.0007, 0.0792],
        [0.0180, 0.0162, 0.0212]], device='cuda:0')

In [15]:
T44=T44.cuda()
T44=1-T44
T44

tensor([[0.9107, 0.1771, 0.1989, 0.4533],
        [0.1430, 0.1852, 0.6440, 0.8556],
        [0.2672, 0.7937, 0.0943, 0.0035],
        [0.7597, 0.9319, 0.3917, 0.1545]], device='cuda:0',
       dtype=torch.float64)

In [16]:
T534=T534.cuda()
T534=T534*2
T534

tensor([[[ 24, 246, 306, 252],
         [298, 220, 360, 270],
         [398, 342, 170,  40]],

        [[332, 382, 260, 318],
         [220, 168, 302, 306],
         [272, 236, 392, 372]],

        [[340, 304, 238,  96],
         [228,  46,  70,  44],
         [218,   4,  64, 334]],

        [[322, 272,  28, 166],
         [254,  88,  88,  94],
         [344, 226, 244,  94]],

        [[  8, 230, 340, 116],
         [178, 258, 156, 144],
         [302, 108, 224, 140]]], device='cuda:0', dtype=torch.int16)

Transpose

In [18]:
T33Trans=T33.t()
T33Trans

tensor([[0.0286, 0.0612, 0.0180],
        [0.0207, 0.0007, 0.0162],
        [0.0570, 0.0792, 0.0212]], device='cuda:0')

In [19]:
T44Trans=T44.t()
T44Trans

tensor([[0.9107, 0.1430, 0.2672, 0.7597],
        [0.1771, 0.1852, 0.7937, 0.9319],
        [0.1989, 0.6440, 0.0943, 0.3917],
        [0.4533, 0.8556, 0.0035, 0.1545]], device='cuda:0',
       dtype=torch.float64)

In [21]:
T534Trans=T534.transpose(1,0)
T534Trans

tensor([[[ 24, 246, 306, 252],
         [332, 382, 260, 318],
         [340, 304, 238,  96],
         [322, 272,  28, 166],
         [  8, 230, 340, 116]],

        [[298, 220, 360, 270],
         [220, 168, 302, 306],
         [228,  46,  70,  44],
         [254,  88,  88,  94],
         [178, 258, 156, 144]],

        [[398, 342, 170,  40],
         [272, 236, 392, 372],
         [218,   4,  64, 334],
         [344, 226, 244,  94],
         [302, 108, 224, 140]]], device='cuda:0', dtype=torch.int16)

Display the Orders and Use Storage

In [29]:
print(T33.storage())
print(T33.storage_offset())
print(T33.contiguous())

 0.02857831120491028
 0.020671159029006958
 0.05703965947031975
 0.061197198927402496
 0.0006930530071258545
 0.07916804403066635
 0.018004221841692924
 0.016237778589129448
 0.021210109815001488
[torch.cuda.FloatStorage of size 9]
0
tensor([[0.0286, 0.0207, 0.0570],
        [0.0612, 0.0007, 0.0792],
        [0.0180, 0.0162, 0.0212]], device='cuda:0')


In [31]:
print(T33Trans.storage())
print(T33Trans.storage_offset())
print(T33Trans.contiguous())

 0.02857831120491028
 0.020671159029006958
 0.05703965947031975
 0.061197198927402496
 0.0006930530071258545
 0.07916804403066635
 0.018004221841692924
 0.016237778589129448
 0.021210109815001488
[torch.cuda.FloatStorage of size 9]
0
tensor([[0.0286, 0.0612, 0.0180],
        [0.0207, 0.0007, 0.0162],
        [0.0570, 0.0792, 0.0212]], device='cuda:0')


In [32]:
print(T44.storage())
print(T44.storage_offset())
print(T44.contiguous())

 0.9106708299141228
 0.17706399367129966
 0.1989255129329608
 0.45334090393083215
 0.14304185563113936
 0.1851902924279527
 0.6440308857626625
 0.8555994707599824
 0.26724500543839214
 0.7937350247330439
 0.09430915004040952
 0.0035106081617334306
 0.7597487038899776
 0.9319391039677039
 0.3916523186781462
 0.15451103513613318
[torch.cuda.DoubleStorage of size 16]
0
tensor([[0.9107, 0.1771, 0.1989, 0.4533],
        [0.1430, 0.1852, 0.6440, 0.8556],
        [0.2672, 0.7937, 0.0943, 0.0035],
        [0.7597, 0.9319, 0.3917, 0.1545]], device='cuda:0',
       dtype=torch.float64)


In [33]:
print(T44Trans.storage())
print(T44Trans.storage_offset())
print(T44Trans.contiguous())

 0.9106708299141228
 0.17706399367129966
 0.1989255129329608
 0.45334090393083215
 0.14304185563113936
 0.1851902924279527
 0.6440308857626625
 0.8555994707599824
 0.26724500543839214
 0.7937350247330439
 0.09430915004040952
 0.0035106081617334306
 0.7597487038899776
 0.9319391039677039
 0.3916523186781462
 0.15451103513613318
[torch.cuda.DoubleStorage of size 16]
0
tensor([[0.9107, 0.1430, 0.2672, 0.7597],
        [0.1771, 0.1852, 0.7937, 0.9319],
        [0.1989, 0.6440, 0.0943, 0.3917],
        [0.4533, 0.8556, 0.0035, 0.1545]], device='cuda:0',
       dtype=torch.float64)


In [34]:
print(T534.storage())
print(T534.storage_offset())
print(T534.contiguous())

 24
 246
 306
 252
 298
 220
 360
 270
 398
 342
 170
 40
 332
 382
 260
 318
 220
 168
 302
 306
 272
 236
 392
 372
 340
 304
 238
 96
 228
 46
 70
 44
 218
 4
 64
 334
 322
 272
 28
 166
 254
 88
 88
 94
 344
 226
 244
 94
 8
 230
 340
 116
 178
 258
 156
 144
 302
 108
 224
 140
[torch.cuda.ShortStorage of size 60]
0
tensor([[[ 24, 246, 306, 252],
         [298, 220, 360, 270],
         [398, 342, 170,  40]],

        [[332, 382, 260, 318],
         [220, 168, 302, 306],
         [272, 236, 392, 372]],

        [[340, 304, 238,  96],
         [228,  46,  70,  44],
         [218,   4,  64, 334]],

        [[322, 272,  28, 166],
         [254,  88,  88,  94],
         [344, 226, 244,  94]],

        [[  8, 230, 340, 116],
         [178, 258, 156, 144],
         [302, 108, 224, 140]]], device='cuda:0', dtype=torch.int16)


In [35]:
print(T534Trans.storage())
print(T534Trans.storage_offset())
print(T534Trans.contiguous())

 24
 246
 306
 252
 298
 220
 360
 270
 398
 342
 170
 40
 332
 382
 260
 318
 220
 168
 302
 306
 272
 236
 392
 372
 340
 304
 238
 96
 228
 46
 70
 44
 218
 4
 64
 334
 322
 272
 28
 166
 254
 88
 88
 94
 344
 226
 244
 94
 8
 230
 340
 116
 178
 258
 156
 144
 302
 108
 224
 140
[torch.cuda.ShortStorage of size 60]
0
tensor([[[ 24, 246, 306, 252],
         [332, 382, 260, 318],
         [340, 304, 238,  96],
         [322, 272,  28, 166],
         [  8, 230, 340, 116]],

        [[298, 220, 360, 270],
         [220, 168, 302, 306],
         [228,  46,  70,  44],
         [254,  88,  88,  94],
         [178, 258, 156, 144]],

        [[398, 342, 170,  40],
         [272, 236, 392, 372],
         [218,   4,  64, 334],
         [344, 226, 244,  94],
         [302, 108, 224, 140]]], device='cuda:0', dtype=torch.int16)


Save Using Torch and h5py

In [45]:
torch.save(T33,"file1.pt")
torch.load("file1.pt")

tensor([[0.0286, 0.0207, 0.0570],
        [0.0612, 0.0007, 0.0792],
        [0.0180, 0.0162, 0.0212]], device='cuda:0')

In [ ]:
#with h5py.File("mytestfile.hdf5", "w") as f:
 #  dset = f.create_dataset("mydataset", )

The Diffrence

In [3]:
a=torch.rand((2,2))
b=torch.rand((2,2),requires_grad=True)
c=torch.rand((2,2))

In [4]:
S=a+b
S.requires_grad

True

In [5]:
S2=a+b
S2.requires_grad

True